# 工作

## 异常处理思考

* 从.NET2.0开始，任何线程上未处理的异常都会导致应用程序的退出（先会触发APPDomain的UnhandledException）

* 如果发生异常，CLR会根据调用栈一层层找到try{}catch{}模块，如果没有找到，就会发生未处理异常,程序终止。

* 主线程无法捕获子线程的异常，具体看子线程和主线程的调用栈。

```c#
string stackInfo = new StackTrace().ToString();
```
### 异常统一处理
windows form程序
```c#
static class Program
    {
        /// <summary>
        /// 应用程序的主入口点。
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);
            Application.ThreadException += new System.Threading.ThreadExceptionEventHandler(Application_ThreadException);
            AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(CurrentDomain_UnhandledException);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

        static void Application_ThreadException(object sender, System.Threading.ThreadExceptionEventArgs e)
        {
            Exception error = e.Exception as Exception;
            //记录日志  
        }

        //有异常未被捕获时触发
        static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            Exception error = e.ExceptionObject as Exception;
            
            //记录日志  
        }
    }
```

该统一处理只能捕获主线程中的异常，其他异常看下面

### task中异常处理
**task中异常处理机制**

task任务抛出异常的时候，task的未处理异常并不会导致程序异常终止，而是在GC垃圾回收器执行的时候，通过TaskScheduler.UnobservedTaskException捕获到task任务抛异常的信息。result、WaitAll和Wait。在用这几个方法的时候，异常会传递到主线程
虽然task中的异常如果不传递到主线程的话，不会导致程序的异常终止，但是这样掩盖了代码中存在bug的隐患，所以还是要对异常进行处理；

处理方法1：内部捕获处理

处理方法2：result、WaitAll和Wait。在用这几个方法的时候，异常会传递到主线程，然后在主线程捕获异常。

处理方法3：ContinueWith

TaskContinuationOptions.OnlyOnFaulted表示只要在有异常发生的时候才调用ContinueWith

```c#
Task.Factory.StartNew(() =>
    {
        testError();
    }).ContinueWith(t => { 
        var exp = t.Exception; 
        //异常处理代码
    }, TaskContinuationOptions.OnlyOnFaulted); 
```

处理方法4：任务调度器TaskScheduler的UnobservedTaskException委托

UnobservedTaskException只有在GC垃圾回收器执行的时候才触发，所以该方法不是实时性的。
```c#
TaskScheduler.UnobservedTaskException += (s, ex) =>
{
    //设置所有未觉察异常被觉察
    ex.SetObserved();
    //异常处理代码
};
Task.Factory.StartNew(() =>
{
    throw new Exception("test");
});
GC.Collect();
GC.WaitForPendingFinalizers();
```

### thread多线程中异常处理
处理方法1：内部进行捕获处理
处理方法2：window form中可以使用窗体的BeginInvoke方法将异常传递给主窗体线程，由主窗体线程进行处理。
```c#
private void test()
{
    Thread thread = new Thread(new ThreadStart(ThreadStart));
    thread.Start();
}

private void ThreadStart()
{
    try
    {
        throw new Exception("test");
    }
    catch (Exception ex)
    {
        this.BeginInvoke((Action)delegate
        {
            throw ex;
        });
    }

}
```

处理方法3：使用事件回调的方式将工作线程的异常包装到主线程。用事件回调的方式处理异常的好处是提供了统一的入口进行异常处理



